### ISSUE TITLE
SS4.12 - ui-helper-hidden

### ISSUE THREAD

**Issue by mspacemedia** [kinglozzer/silverstripe-multiselectfield#17] opened 2022-11-09 11:44 UTC
The class `ui-helper-hidden` is being added to the `span` in each `li` so no Titles show up in the latest build of SilverStripe

**Comment by kinglozzer** [comment] 2022-11-09 15:29
Hmm, I think is likely caused by the upgrade to `jquery` (and presumably `jquery-ui`) coming in `4.12`. I don’t think it’s very likely that the multiselect library that this module uses has been updated, so this might need to just be fixed by some specific CSS to override the `display: none`

As a workaround for now you should be able to do just that. Add a CSS file to `LeftAndMain.extra_requirements_css` if you don’t have one already, and find an appropriate CSS selector... something along the lines of `.multiselect li > span.ui-helper-hidden { display: block; }`

**Comment by mspacemedia** [comment] 2022-11-15 13:25
Worse, the change to JQuery 3.6 in 4.12.0 has broken the JS completely - now longer allows drag and drop or double click to switch selections…

`Uncaught TypeError: can't access property "attr", item.data(...) is undefined
    _setSelected https://site.com/_resources/vendor/kinglozzer/multiselectfield/client/thirdparty/multiselect/js/ui.multiselect.js?m=1554904131:176
ui.multiselect.js:176:8`

**Comment by mspacemedia** [comment] 2022-11-15 14:53
This may also be a part of any issues with the old multiselect.js too as the module js uses onmatch

https://docs.silverstripe.org/en/4/changelogs/beta/4.12.0-beta1/#jquery-entwine-change

**Comment by kinglozzer** [comment] 2022-11-16 15:51
Ah 💩, that might be the end of the road for this module then, at least in the format it currently exists in. It uses this version of multiselect https://github.com/michael/multiselect which has numerous open issues about jQuery 3 and recent jQuery UI versions. If there are a few one-line fixes that can be hacked in to make this work then I’m all for it, but I don’t think it’s worth spending much time on given how out of date the underlying library is.

For now I’d probably switch to using `GridFieldAddExistingAutocompleter` and `GridFieldOrderableRows`. That UI isn’t as quick as clicking a plus/minus to add/remove items, but it’s functional.

**Comment by mspacemedia** [comment] 2022-11-16 17:36
😀 Such a shame as it's littered throughout various sites…

**Comment by nicolas-cusan** [comment] 2023-02-14 16:43
For anyone wanting to use this fields in SilverStripe 4.12+. We created a fork with updated JavaScript https://github.com/arillo-ch/silverstripe-multiselectfield

**Comment by kinglozzer** [comment] 2023-03-17 09:48
Fixed in 2.0.2

**Closed** 2023-03-17 09:48 UTC
